In [47]:
import requests # Library for HTTP requests
import pandas as pd 

# Petfinder credentials

client_id = "UhZz5tt8FKSRvLxy3KZgAQlqgEwkDp2SQz2j3ER6cywsSbIQUf"
client_secret = "nrnNidv1AsGHZYVC7jNFWGnB9QIu30TuzMfCkxXB"

# Request access token from Petfinder

token_url = "https://api.petfinder.com/v2/oauth2/token"
payload = {
    "grant_type": "client_credentials",
    "client_id": client_id,
    "client_secret": client_secret
}

response = requests.post(token_url, data=payload) # Get the token
access_token = response.json()['access_token'] # Extract the token 
print(access_token) # Show the token

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJVaFp6NXR0OEZLU1J2THh5M0taZ0FRbHFnRXdrRHAyU1F6MmozRVI2Y3l3c1NiSVFVZiIsImp0aSI6ImFlMGE1YjBhMmJmZTA2MWE2MjNiNmYzMTYxNmM1NzRjMWQxYjg3ZTg2NDUwMzI4ZDMyNjBmZjk0NTczNTc5MGZmNzFhN2EzNDkwNWI3ODdmIiwiaWF0IjoxNzUxOTE4MTI1LCJuYmYiOjE3NTE5MTgxMjUsImV4cCI6MTc1MTkyMTcyNSwic3ViIjoiIiwic2NvcGVzIjpbXX0.TAGzuIAyc14MSFXZuWRBSOkHC9dG9Sk9qf_W5GYg_fWIaxygmk5wIfffg43nXe9mX_6iIz9-dRGGdo9_8wJ9WxIYHOSFWnThyuJkqu3TcRQ8hB48Q0pIJiNGDsggrxlDTfsy1G4FC6cFv6fU_NNwhrP9McDTKDfaDC-gA2U0QfU4zxUHrNrx3XycjVgU30W4acFxQ0HxOIl-mJ2xHDfoujRanCB29P6rF8HtCZ_V3BJsWjuwnDiAAExu-YLZAHkk-gF-ZSHdNKmuOeB_W-qgoVkN8_SFfbuppD5zB48RDjT-s4VL3rvzQoFZwsMEDd-xD7XGMW_wbgFTN5SuwXc02A

In [48]:
headers = {"Authorization": f"Bearer {access_token}"}  # Auth header with API token
params = {"type": "dog", "location": "New York"}  # Filter for dogs in New York
url = "https://api.petfinder.com/v2/animals" # URL for where to send the request 

response = requests.get(url, headers=headers, params=params)  # Send the request
data = response.json()  # Convert the result into a Python data structure

In [49]:
df = pd.DataFrame(data['animals'])
df.head()

,id,organization_id,url,type,species,breeds,colors,age,gender,size,...,organization_animal_id,photos,primary_photo_cropped,videos,status,status_changed_at,published_at,distance,contact,_links
0,77185584,PA19,https://www.petfinder.com/dog/dusty-77185584/p...,Dog,Dog,"{'primary': 'Cocker Spaniel', 'secondary': Non...","{'primary': 'Brown / Chocolate', 'secondary': ...",Adult,Male,Medium,...,None,[{'small': 'https://dbw3zep4prcju.cloudfront.n...,{'small': 'https://dbw3zep4prcju.cloudfront.ne...,[],adoptable,2025-07-07T15:58:38+0000,2025-07-07T15:58:36+0000,94.7551,"{'email': 'bradfordchs@cableracer.com', 'phone...","{'self': {'href': '/v2/animals/77185584'}, 'ty..."
1,77183048,NY71,https://www.petfinder.com/dog/meadow-may-77183...,Dog,Dog,"{'primary': 'Coonhound', 'secondary': None, 'm...","{'primary': 'Brown / Chocolate', 'secondary': ...",Baby,Female,Small,...,BCNY-A-38580,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,None,[],adoptable,2025-07-07T10:46:38+0000,2025-07-07T10:46:37+0000,65.8260,"{'email': 'info@bchumanesoc.com', 'phone': '(6...","{'self': {'href': '/v2/animals/77183048'}, 'ty..."
2,77181215,NY494,https://www.petfinder.com/dog/sara-77181215/ny...,Dog,Dog,"{'primary': 'Mixed Breed', 'secondary': None, ...","{'primary': 'Red / Chestnut / Orange', 'second...",Adult,Female,Large,...,LPNY-A-279866,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T09:52:56+0000,2025-07-07T09:52:54+0000,95.9562,"{'email': 'adoptions@lollypop.org', 'phone': '...","{'self': {'href': '/v2/animals/77181215'}, 'ty..."
3,77180587,NY1357,https://www.petfinder.com/dog/frankie-77180587...,Dog,Dog,"{'primary': 'Husky', 'secondary': None, 'mixed...","{'primary': 'Black', 'secondary': None, 'terti...",Young,Female,Medium,...,NCPA-A-18003,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T09:10:42+0000,2025-07-07T09:10:40+0000,49.3014,"{'email': 'info@northcountrypetadoption.org', ...","{'self': {'href': '/v2/animals/77180587'}, 'ty..."
4,77179681,NY712,https://www.petfinder.com/dog/mn-bentley-77179...,Dog,Dog,"{'primary': 'Brittany Spaniel', 'secondary': N...","{'primary': None, 'secondary': None, 'tertiary...",Young,Male,Medium,...,21467299-25-0079,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T05:11:34+0000,2025-07-07T05:11:32+0000,43.4289,"{'email': 'JBBSTUDIO@comcast.net', 'phone': No...","{'self': {'href': '/v2/animals/77179681'}, 'ty..."

In [50]:
all_animals = []  # List to store all dogs
page = 1 # Start with page 1 
limit = 40  # Dogs per page

while True: # Start an infinite loop 
    params = {"type": "dog", "location": "New York", "page": page, "limit": limit} # Set parameters 
    response = requests.get(url, headers=headers, params=params) # Sends request to API 
    data = response.json() # Converts the APIâ€™s JSON response into a Python dictionary.
    animals = data.get('animals', [])  # Dogs from this page
    all_animals.extend(animals)        # Add to main list
    if len(animals) < limit:           # No more pages left
        break
    page += 1

print(len(all_animals))  # Print total number of dogs

1201

In [51]:
import pandas as pd

df = pd.DataFrame(all_animals) # Create a dataframe

pd.set_option('display.max_rows', None) # Show all rows displaying the dataframe
df.head(10) # Show last 10

,id,organization_id,url,type,species,breeds,colors,age,gender,size,...,organization_animal_id,photos,primary_photo_cropped,videos,status,status_changed_at,published_at,distance,contact,_links
0,77185584,PA19,https://www.petfinder.com/dog/dusty-77185584/p...,Dog,Dog,"{'primary': 'Cocker Spaniel', 'secondary': Non...","{'primary': 'Brown / Chocolate', 'secondary': ...",Adult,Male,Medium,...,None,[{'small': 'https://dbw3zep4prcju.cloudfront.n...,{'small': 'https://dbw3zep4prcju.cloudfront.ne...,[],adoptable,2025-07-07T15:58:38+0000,2025-07-07T15:58:36+0000,94.7551,"{'email': 'bradfordchs@cableracer.com', 'phone...","{'self': {'href': '/v2/animals/77185584'}, 'ty..."
1,77183048,NY71,https://www.petfinder.com/dog/meadow-may-77183...,Dog,Dog,"{'primary': 'Coonhound', 'secondary': None, 'm...","{'primary': 'Brown / Chocolate', 'secondary': ...",Baby,Female,Small,...,BCNY-A-38580,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,None,[],adoptable,2025-07-07T10:46:38+0000,2025-07-07T10:46:37+0000,65.8260,"{'email': 'info@bchumanesoc.com', 'phone': '(6...","{'self': {'href': '/v2/animals/77183048'}, 'ty..."
2,77181215,NY494,https://www.petfinder.com/dog/sara-77181215/ny...,Dog,Dog,"{'primary': 'Mixed Breed', 'secondary': None, ...","{'primary': 'Red / Chestnut / Orange', 'second...",Adult,Female,Large,...,LPNY-A-279866,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T09:52:56+0000,2025-07-07T09:52:54+0000,95.9562,"{'email': 'adoptions@lollypop.org', 'phone': '...","{'self': {'href': '/v2/animals/77181215'}, 'ty..."
3,77180587,NY1357,https://www.petfinder.com/dog/frankie-77180587...,Dog,Dog,"{'primary': 'Husky', 'secondary': None, 'mixed...","{'primary': 'Black', 'secondary': None, 'terti...",Young,Female,Medium,...,NCPA-A-18003,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T09:10:42+0000,2025-07-07T09:10:40+0000,49.3014,"{'email': 'info@northcountrypetadoption.org', ...","{'self': {'href': '/v2/animals/77180587'}, 'ty..."
4,77179681,NY712,https://www.petfinder.com/dog/mn-bentley-77179...,Dog,Dog,"{'primary': 'Brittany Spaniel', 'secondary': N...","{'primary': None, 'secondary': None, 'tertiary...",Young,Male,Medium,...,21467299-25-0079,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T05:11:34+0000,2025-07-07T05:11:32+0000,43.4289,"{'email': 'JBBSTUDIO@comcast.net', 'phone': No...","{'self': {'href': '/v2/animals/77179681'}, 'ty..."
5,77178567,NY1705,https://www.petfinder.com/dog/ginny-77178567/n...,Dog,Dog,"{'primary': 'American Bulldog', 'secondary': '...","{'primary': 'Gray / Blue / Silver', 'secondary...",Adult,Female,Medium,...,ps_2451617-3751649,[{'small': 'https://dl5zpyw5k3jeb.cloudfront.n...,{'small': 'https://dl5zpyw5k3jeb.cloudfront.ne...,[],adoptable,2025-07-07T04:04:52+0000,2025-07-07T04:04:50+0000,18.7154,"{'email': 'roversdoover@gmail.com', 'phone': N...","{'self': {'href': '/v2/animals/77178567'}, 'ty..."
6,77178165,TX2305,https://www.petfinder.com/dog/zumba-77178165/n...,Dog,Dog,"{'primary': 'English Pointer', 'secondary': 'L...","{'primary': 'Black', 'secondary': 'White / Cre...",Young,Female,Medium,...,None,[{'small': 'https://dbw3zep4prcju.cloudfront.n...,{'small': 'https://dbw3zep4prcju.cloudfront.ne...,[],adoptable,2025-07-07T03:01:15+0000,2025-07-07T03:01:13+0000,92.2769,"{'email': 'rescue@throwadogabone.org', 'phone'...","{'self': {'href': '/v2/animals/77178165'}, 'ty..."
7,77177815,TX2305,https://www.petfinder.com/dog/rosie-77177815/n...,Dog,Dog,{'primary': 'Australian Cattle Dog / Blue Heel...,"{'primary': 'Black', 'secondary': 'White / Cre...",Baby,Female,Medium,...,None,[{'small': 'https://dbw3zep4prcju.cloudfront.n...,{'small': 'https://dbw3zep4prcju.cloudfront.ne...,[],adoptable,2025-07-07T02:21:43+0000,2025-07-07T02:21:42+0000,29.4125,"{'email': 'rescue@throwadogabone.org', 'phone'...","{'self': {'href': '/v2/animals/77177815'}, 'ty..."
8,77177766,NY1667,https://www.petfinder.com/dog/glimmer-77177766...,Dog,Dog,"{'primary': 'Pit Bull Terrier', 'secondary': N...","{'primary': None, 'secondary': None, 'tertiary...",Baby,Female,Medium,...,None,[{'small': 'https://dbw3zep4prcju.cloudfront.n...,{'small': 'https://dbw3zep4prcju.cloudfront.ne...,[],adoptable,2025-07-07T02:10:24+0000,2025-07-07T02:10:23+0000,91.4305,"{'email': 'Paws.saved.by.chrissy@gmail.com', '...","{'self': {'href': '/v2/animals/77177766'}, 'ty..."
9,77177072,NY966,https://www.petfinder.com/dog/aphrodite-771770...,Dog,Dog,"{'primary': 'Catahoula Leopard Dog', 'secondar...","{'primary': 'Black', 'secondary': 'White / Cre...",Baby,Female,Medium,...,None,[{'small': 'https://dbw3zep4prcju.cloudfront.n...,{'small': 'https://dbw3zep4prcju.cloudfront.ne...,[],adoptable,2025-07-07T00:34:08+0000,2025-07-07T00:34:07+0000,58.4285,"{'email': 'pibblesrus33@gmail.com', 'phone': N...","{'self': {'href': '/v2/animals/77177072'}, 'ty..."

## Top breeds (looking at primary breeds)

In [92]:
# Exclude 'Mixed Breed'
purebred = df[df['primary_breed'] != 'Mixed Breed']

# Counts for each breed (excluding mixed)
counts = purebred['primary_breed'].value_counts(dropna=False)

# Percentages for each breed (excluding mixed)
percentages = purebred['primary_breed'].value_counts(normalize=True, dropna=False) * 100

breed_stats = pd.DataFrame({'count': counts, 'percentage': percentages.round(1)})

print(breed_stats)

                                          count  percentage
primary_breed
Pit Bull Terrier                            186        18.2
Labrador Retriever                           75         7.3
Terrier                                      60         5.9
American Staffordshire Terrier               52         5.1
German Shepherd Dog                          48         4.7
Chihuahua                                    38         3.7
Boxer                                        36         3.5
Husky                                        34         3.3
Shepherd                                     32         3.1
Hound                                        31         3.0
American Bulldog                             22         2.1
Australian Shepherd                          21         2.1
Black Labrador Retriever                     19         1.9
Border Collie                                17         1.7
Australian Cattle Dog / Blue Heeler          14         1.4
American Bully                               14         1.4
Siberian Husky                               12         1.2
Black Mouth Cur                              12         1.2
Great Pyrenees                               11         1.1
Jack Russell Terrier                         11         1.1
Rat Terrier                                  11         1.1
Rottweiler                                   10         1.0
Beagle                                       10         1.0
Mastiff                                       9         0.9
Pug                                           9         0.9
Dachshund                                     9         0.9
Staffordshire Bull Terrier                    9         0.9
Catahoula Leopard Dog                         9         0.9
Pomeranian                                    8         0.8
Poodle                                        7         0.7
Cattle Dog                                    6         0.6
Shih Tzu                                      6         0.6
Treeing Walker Coonhound                      6         0.6
Retriever                                     5         0.5
Bloodhound                                    5         0.5
Great Dane                                    5         0.5
Mountain Cur                                  5         0.5
Yellow Labrador Retriever                     4         0.4
Cane Corso                                    4         0.4
German Shorthaired Pointer                    4         0.4
English Bulldog                               4         0.4
French Bulldog                                4         0.4
Pointer                                       4         0.4
Golden Retriever                              4         0.4
Shiba Inu                                     4         0.4
Coonhound                                     4         0.4
Bull Terrier                                  4         0.4
Carolina Dog                                  3         0.3
Akita                                         3         0.3
Doberman Pinscher                             3         0.3
Alaskan Malamute                              3         0.3
Puggle                                        3         0.3
Bulldog                                       3         0.3
Boston Terrier                                3         0.3
Chow Chow                                     3         0.3
Plott Hound                                   3         0.3
Anatolian Shepherd                            3         0.3
Greyhound                                     3         0.3
Lhasa Apso                                    3         0.3
Collie                                        2         0.2
Bluetick Coonhound                            2         0.2
Havanese                                      2         0.2
Shar-Pei                                      2         0.2
Poodle (Toy)                                  2         0.2
Miniature Pinscher                            2         0.2
Samoyed                                       2         0.2
Dalmatian                                     2         0.2
Schnauzer                                     2         0.2
Cocker Spaniel                                2         0.2
Dutch Shepherd                                2         0.2
Yorkshire Terrier                             2         0.2
Belgian Shepherd / Malinois                   2         0.2
Maltese                                       2         0.2
Bichon Frise                                  2         0.2
Spaniel                                       2         0.2
Newfoundland Dog                              2         0.2
Rhodesian Ridgeback                           2         0.2
Labradoodle                                   2         0.2
Miniature Poodle                              2         0.2
Caucasian Sheepdog / Caucasian Ovtcharka      2         0.2
Canaan Dog                                    2         0.2
Feist                                         1         0.1
American Foxhound                             1         0.1
German Longhaired Pointer                     1         0.1
English Pointer                               1         0.1
Bullmastiff                                   1         0.1
Pembroke Welsh Corgi                          1         0.1
English Coonhound                             1         0.1
Brittany Spaniel                              1         0.1
English Springer Spaniel                      1         0.1
Wheaten Terrier                               1         0.1
Boerboel                                      1         0.1
Chinese Crested Dog                           1         0.1
Jindo                                         1         0.1
Goldendoodle                                  1         0.1
Giant Schnauzer                               1         0.1
Weimaraner                                    1         0.1
Foxhound                                      1         0.1
Chocolate Labrador Retriever                  1         0.1
Shetland Sheepdog / Sheltie                   1         0.1
Aussiedoodle                                  1         0.1
Affenpinscher                                 1         0.1
Cairn Terrier                                 1         0.1
Ibizan Hound                                  1         0.1
Maremma Sheepdog                              1         0.1
Border Terrier                                1         0.1
Shorkie                                       1         0.1
Redbone Coonhound                             1         0.1
Cardigan Welsh Corgi                          1         0.1
Wirehaired Dachshund                          1         0.1
Bernese Mountain Dog                          1         0.1

In [90]:
len(all_animals)

1201

In [53]:
# Extract primary color
df['primary_color'] = df['colors'].apply(lambda c: c.get('primary') if isinstance(c, dict) else None)

# Count by primary color
print(df['primary_color'].value_counts(dropna=False))

primary_color
None                                418
Black                               209
White / Cream                       113
Brown / Chocolate                    90
Yellow / Tan / Blond / Fawn          85
Tricolor (Brown, Black, & White)     63
Brindle                              55
Gray / Blue / Silver                 44
Apricot / Beige                      41
Red / Chestnut / Orange              24
Bicolor                              23
Golden                               16
Merle (Blue)                          6
Sable                                 5
Harlequin                             5
Merle (Red)                           4
Name: count, dtype: int64

In [54]:
print(df['age'].value_counts(dropna=False)) # What ages are the dogs

age
Adult     639
Young     320
Baby      165
Senior     77
Name: count, dtype: int64

## Clean the data

In [55]:
# Select the columns I want and make a copy
cleaned_dogs = df[['name', 'primary_breed', 'age', 'size', 'gender', 'colors', 'published_at', 'organization_id']].copy()
# color from the 'colors' dict into a new column
cleaned_dogs['colour (primary)'] = cleaned_dogs['colors'].apply(
    lambda x: x.get('primary') if isinstance(x, dict) else None
)

# 3. Drop the original 'colors' column
cleaned_dogs = cleaned_dogs.drop(columns=['colors'])

cleaned_dogs.head()

,name,primary_breed,age,size,gender,published_at,organization_id,colour (primary)
0,Dusty,Cocker Spaniel,Adult,Medium,Male,2025-07-07T15:58:36+0000,PA19,Brown / Chocolate
1,Meadow May,Coonhound,Baby,Small,Female,2025-07-07T10:46:37+0000,NY71,Brown / Chocolate
2,Sara,Mixed Breed,Adult,Large,Female,2025-07-07T09:52:54+0000,NY494,Red / Chestnut / Orange
3,Frankie,Husky,Young,Medium,Female,2025-07-07T09:10:40+0000,NY1357,Black
4,MN/Bentley,Brittany Spaniel,Young,Medium,Male,2025-07-07T05:11:32+0000,NY712,None

In [56]:
cleaned_dogs = cleaned_dogs[['name', 'primary_breed', 'age', 'size', 'gender', 'colour (primary)', 'published_at','organization_id']] # Change the order

In [57]:
cleaned_dogs.head()

,name,primary_breed,age,size,gender,colour (primary),published_at,organization_id
0,Dusty,Cocker Spaniel,Adult,Medium,Male,Brown / Chocolate,2025-07-07T15:58:36+0000,PA19
1,Meadow May,Coonhound,Baby,Small,Female,Brown / Chocolate,2025-07-07T10:46:37+0000,NY71
2,Sara,Mixed Breed,Adult,Large,Female,Red / Chestnut / Orange,2025-07-07T09:52:54+0000,NY494
3,Frankie,Husky,Young,Medium,Female,Black,2025-07-07T09:10:40+0000,NY1357
4,MN/Bentley,Brittany Spaniel,Young,Medium,Male,None,2025-07-07T05:11:32+0000,NY712

In [58]:
len(cleaned_dogs) # Count

1201

In [59]:
# Convert 'published_at' to datetime and format as 'YYYY-MM'

cleaned_dogs['published_at'] = pd.to_datetime(cleaned_dogs['published_at'], errors='coerce').dt.strftime('%Y-%m')

In [61]:
cleaned_dogs.head()

,name,primary_breed,age,size,gender,colour (primary),published_at,organization_id
0,Dusty,Cocker Spaniel,Adult,Medium,Male,Brown / Chocolate,2025-07,PA19
1,Meadow May,Coonhound,Baby,Small,Female,Brown / Chocolate,2025-07,NY71
2,Sara,Mixed Breed,Adult,Large,Female,Red / Chestnut / Orange,2025-07,NY494
3,Frankie,Husky,Young,Medium,Female,Black,2025-07,NY1357
4,MN/Bentley,Brittany Spaniel,Young,Medium,Male,None,2025-07,NY712

In [62]:
# Double checking how much there is of everything
breed_counts = cleaned_dogs['primary_breed'].value_counts()
age_counts = cleaned_dogs['age'].value_counts()
size_counts = cleaned_dogs['size'].value_counts()
gender_counts = cleaned_dogs['gender'].value_counts()

print(breed_counts)
print(age_counts)
print(size_counts)
print(gender_counts)

primary_breed
Pit Bull Terrier                            186
Mixed Breed                                 177
Labrador Retriever                           75
Terrier                                      60
American Staffordshire Terrier               52
German Shepherd Dog                          48
Chihuahua                                    38
Boxer                                        36
Husky                                        34
Shepherd                                     32
Hound                                        31
American Bulldog                             22
Australian Shepherd                          21
Black Labrador Retriever                     19
Border Collie                                17
American Bully                               14
Australian Cattle Dog / Blue Heeler          14
Siberian Husky                               12
Black Mouth Cur                              12
Rat Terrier                                  11
Great Pyrenees                               11
Jack Russell Terrier                         11
Beagle                                       10
Rottweiler                                   10
Catahoula Leopard Dog                         9
Dachshund                                     9
Staffordshire Bull Terrier                    9
Pug                                           9
Mastiff                                       9
Pomeranian                                    8
Poodle                                        7
Cattle Dog                                    6
Shih Tzu                                      6
Treeing Walker Coonhound                      6
Retriever                                     5
Bloodhound                                    5
Great Dane                                    5
Mountain Cur                                  5
Yellow Labrador Retriever                     4
Cane Corso                                    4
German Shorthaired Pointer                    4
English Bulldog                               4
French Bulldog                                4
Pointer                                       4
Golden Retriever                              4
Shiba Inu                                     4
Coonhound                                     4
Bull Terrier                                  4
Alaskan Malamute                              3
Akita                                         3
Doberman Pinscher                             3
Carolina Dog                                  3
Puggle                                        3
Bulldog                                       3
Boston Terrier                                3
Chow Chow                                     3
Plott Hound                                   3
Anatolian Shepherd                            3
Greyhound                                     3
Lhasa Apso                                    3
Collie                                        2
Bluetick Coonhound                            2
Havanese                                      2
Shar-Pei                                      2
Poodle (Toy)                                  2
Miniature Pinscher                            2
Samoyed                                       2
Dalmatian                                     2
Schnauzer                                     2
Cocker Spaniel                                2
Dutch Shepherd                                2
Yorkshire Terrier                             2
Belgian Shepherd / Malinois                   2
Maltese                                       2
Bichon Frise                                  2
Spaniel                                       2
Newfoundland Dog                              2
Rhodesian Ridgeback                           2
Labradoodle                                   2
Miniature Poodle                              2
Caucasian Sheepdog / Caucasian Ovtcharka      2
Canaan Dog                                    2
Feist                                         1
American Foxhound                             1
German Longhaired Pointer                     1
English Pointer                               1
Bullmastiff                                   1
Pembroke Welsh Corgi                          1
English Coonhound                             1
Brittany Spaniel                              1
English Springer Spaniel                      1
Wheaten Terrier                               1
Boerboel                                      1
Chinese Crested Dog                           1
Jindo                                         1
Goldendoodle                                  1
Giant Schnauzer                               1
Weimaraner                                    1
Foxhound                                      1
Chocolate Labrador Retriever                  1
Shetland Sheepdog / Sheltie                   1
Aussiedoodle                                  1
Affenpinscher                                 1
Cairn Terrier                                 1
Ibizan Hound                                  1
Maremma Sheepdog                              1
Border Terrier                                1
Shorkie                                       1
Redbone Coonhound                             1
Cardigan Welsh Corgi                          1
Wirehaired Dachshund                          1
Bernese Mountain Dog                          1
Name: count, dtype: int64
age
Adult     639
Young     320
Baby      165
Senior     77
Name: count, dtype: int64
size
Medium         651
Large          366
Small          162
Extra Large     22
Name: count, dtype: int64
gender
Male      649
Female    552
Name: count, dtype: int64

In [63]:
print(df.columns)

Index(['id', 'organization_id', 'url', 'type', 'species', 'breeds', 'colors',
       'age', 'gender', 'size', 'coat', 'attributes', 'environment', 'tags',
       'name', 'description', 'organization_animal_id', 'photos',
       'primary_photo_cropped', 'videos', 'status', 'status_changed_at',
       'published_at', 'distance', 'contact', '_links', 'primary_breed',
       'primary_color'],
      dtype='object')

In [64]:
cleaned_dogs.head()

,name,primary_breed,age,size,gender,colour (primary),published_at,organization_id
0,Dusty,Cocker Spaniel,Adult,Medium,Male,Brown / Chocolate,2025-07,PA19
1,Meadow May,Coonhound,Baby,Small,Female,Brown / Chocolate,2025-07,NY71
2,Sara,Mixed Breed,Adult,Large,Female,Red / Chestnut / Orange,2025-07,NY494
3,Frankie,Husky,Young,Medium,Female,Black,2025-07,NY1357
4,MN/Bentley,Brittany Spaniel,Young,Medium,Male,None,2025-07,NY712

## Closer look at the pit bull terrier

In [85]:
# Exclude rows where the breed is 'Mixed Breed'
filtered = cleaned_dogs[cleaned_dogs['primary_breed'] != 'Mixed Breed']

# Group by breed, age, size, and gender, and count occurrences
combo_counts = (
    filtered.groupby(['primary_breed', 'age', 'size', 'gender'])
    .size()
    .reset_index(name='count')
    .sort_values('count', ascending=False)
)

# Get the most common combination
most_typical = combo_counts.iloc[0]

# Display result
print("Most typical dog up for adoption (excluding Mixed Breed):")
print(f"Breed: {most_typical['primary_breed']}")
print(f"Age: {most_typical['age']}")
print(f"Size: {most_typical['size']}")
print(f"Gender: {most_typical['gender']}")
print(f"Listings: {most_typical['count']}")

Most typical dog up for adoption (excluding Mixed Breed):
Breed: Pit Bull Terrier
Age: Adult
Size: Large
Gender: Male
Listings: 39

In [72]:
unique_shelters = {animal['organization_id'] for animal in all_animals}
num_shelters = len(unique_shelters)
print(f"Number of different shelters: {num_shelters}")

Number of different shelters: 140

In [73]:
from collections import Counter

# Count all animals per shelter
shelter_counts = Counter(animal.get('organization_id') for animal in all_animals)

print("Top 5 shelters by total animals:")
for shelter, count in shelter_counts.most_common(5):
    print(f"{shelter}: {count} animals")

Top 5 shelters by total animals:
NY106: 60 animals
NY480: 54 animals
NY512: 47 animals
NY1705: 46 animals
NY1550: 41 animals

In [74]:
# Define pitbulls first:
pitbulls = cleaned_dogs[cleaned_dogs['primary_breed'].str.lower() == 'pit bull terrier']

# Now you can count:
shelter_counts = pitbulls['organization_id'].value_counts()
if not shelter_counts.empty:
    top_shelter = shelter_counts.idxmax()
    top_count = shelter_counts.max()
    print(f"Shelter with the most Pit Bull Terriers: {top_shelter} ({top_count} pit bulls)")
else:
    print("No Pit Bull Terriers found in the data.")

Shelter with the most Pit Bull Terriers: NY512 (28 pit bulls)

In [75]:
# Pitbulls in shelter NY512
pitbulls = cleaned_dogs[cleaned_dogs['primary_breed'].str.lower() == 'pit bull terrier']

# Filter for shelter NY512
pitbulls_ny512 = pitbulls[pitbulls['organization_id'] == 'NY512']

# Display their details
print(pitbulls_ny512[['name', 'age', 'size', 'gender', 'published_at']])

                   name     age    size  gender published_at
170                 Pat   Adult  Medium    Male      2025-06
322                Nova   Young  Medium  Female      2025-06
433             Jackson   Adult  Medium    Male      2025-06
538                 Avi   Adult   Large    Male      2025-05
771                Lily   Adult  Medium  Female      2025-04
812               Sasha   Adult   Large  Female      2025-03
813                Liam   Adult  Medium    Male      2025-03
814                Duke   Adult  Medium    Male      2025-03
815                Milo   Adult  Medium    Male      2025-03
827                Thor   Adult  Medium    Male      2025-03
828              Navada   Adult  Medium    Male      2025-03
843               Rocky   Adult   Large    Male      2025-03
864               Henry   Adult  Medium    Male      2025-02
865                Dior   Young  Medium  Female      2025-02
889            Blizzard   Adult  Medium  Female      2025-02
893                King   Adult   Large    Male      2025-02
900               Gemma   Adult  Medium  Female      2025-01
911               Kylie   Adult  Medium  Female      2025-01
973              Crosby   Adult  Medium    Male      2024-10
977   Amazing Angel Lyn  Senior   Large  Female      2024-10
986            Stallone   Adult  Medium    Male      2024-10
997               Frank  Senior  Medium    Male      2024-09
1007              Frodo   Adult   Large    Male      2024-08
1015               Hula   Adult   Large  Female      2024-08
1016             Chance   Adult   Large    Male      2024-08
1042         Butterball   Adult  Medium    Male      2024-06
1063             Tanner   Adult   Large    Male      2024-04
1091              Larry   Adult   Large    Male      2024-02

In [78]:
# Count pit bulls per shelter
shelter_counts = pitbulls['organization_id'].value_counts()

print("Top 10 shelters by number of Pit Bull Terriers:")
for shelter, count in shelter_counts.head(10).items():
    print(f"{shelter}: {count} pit bulls")

Top 10 shelters by number of Pit Bull Terriers:
NY512: 28 pit bulls
NY1705: 18 pit bulls
NY106: 15 pit bulls
NY966: 11 pit bulls
PA803: 7 pit bulls
PA59: 7 pit bulls
NY1690: 7 pit bulls
NY1102: 5 pit bulls
NY1550: 5 pit bulls
NY360: 5 pit bulls

In [79]:
# Pitbulls in shelter NY1705
pitbulls = cleaned_dogs[cleaned_dogs['primary_breed'].str.lower() == 'pit bull terrier']

# Filter for shelter 
pitbulls_ny1705 = pitbulls[pitbulls['organization_id'] == 'NY1705']

# Display their details
print(pitbulls_ny1705[['name', 'age', 'size', 'gender', 'published_at']])

           name    age    size  gender published_at
97   Clementine  Adult  Medium  Female      2025-07
275       Raven  Young  Medium  Female      2025-06
276      Indigo   Baby  Medium  Female      2025-06
278        Navy   Baby  Medium    Male      2025-06
279        Blue  Adult  Medium    Male      2025-06
281        Navy   Baby  Medium    Male      2025-06
282        Blue  Adult  Medium    Male      2025-06
284   Scarlette   Baby  Medium  Female      2025-06
287       Coral   Baby  Medium  Female      2025-06
288        Onyx   Baby  Medium    Male      2025-06
289        Grey  Adult  Medium    Male      2025-06
349       Betty  Adult  Medium  Female      2025-06
358       Creed  Adult   Large    Male      2025-06
458        Tony  Adult  Medium    Male      2025-06
459        Kyle  Adult   Large    Male      2025-06
625    Rhaenyra  Adult   Large  Female      2025-05
626      Edison  Adult  Medium    Male      2025-05
631      Ginger  Adult   Large  Female      2025-05

In [80]:
import pandas as pd

# ... (previous steps are the same)

# Calculate the proportion of pit bulls per shelter
pitbull_share = (pitbulls_per_shelter / total_per_shelter).fillna(0)

# Find shelters where more than 20% of the dogs are pit bulls (>0.2)
pitbull_20pct_shelters = pitbull_share[pitbull_share > 0.2]

# Count those shelters
num_20pct_pitbull = pitbull_20pct_shelters.count()

print(f"Number of shelters where more than 20% of the dogs are pit bull terriers: {num_20pct_pitbull}")
print("Shelter IDs with more than 20% pit bulls:")
print(pitbull_20pct_shelters)

Number of shelters where more than 20% of the dogs are pit bull terriers: 29
Shelter IDs with more than 20% pit bulls:
organization_id
CT116     0.500000
NY1041    0.571429
NY106     0.250000
NY1102    0.555556
NY1119    0.555556
NY132     0.230769
NY1441    0.285714
NY1498    0.500000
NY1511    1.000000
NY1658    1.000000
NY1690    0.875000
NY1705    0.391304
NY192     0.500000
NY234     0.428571
NY311     0.500000
NY430     1.000000
NY508     0.222222
NY512     0.595745
NY52      0.266667
NY633     0.250000
NY701     0.400000
NY79      0.428571
NY907     0.400000
NY966     0.647059
PA59      0.636364
PA803     0.225806
PA981     0.333333
TX2109    0.285714
TX859     1.000000
dtype: float64

In [81]:
total_dogs = len(cleaned_dogs)
pitbulls_count = (cleaned_dogs['primary_breed'].str.lower() == 'pit bull terrier').sum()
pitbull_share = pitbulls_count / total_dogs
print(f"Pit bulls make up {pitbull_share:.1%} of all adoptable dogs.") #This when you include mixed breeds

Pit bulls make up 15.5% of all adoptable dogs.

In [82]:
# Define your bully breeds list
bully_breeds = [
    "pit bull terrier",
    "american pit bull terrier",
    "american staffordshire terrier",
    "staffordshire bull terrier",
    "american bulldog",
    "bull terrier",
    "american bully",
    "bullmastiff",
    "mastiff",
    "cane corso",
    "boxer"
]

# Create a Boolean Series for bully breed status
is_bully = cleaned_dogs['primary_breed'].str.lower().isin(bully_breeds)

# Add this as a column to DataFrame
cleaned_dogs['is_bully'] = is_bully

# Calculate the count and percentage
bully_count = is_bully.sum()
total_count = len(cleaned_dogs)
bully_percentage = 100 * bully_count / total_count

print(f"{bully_count} out of {total_count} dogs are bully breeds ({bully_percentage:.1f}%)")

337 out of 1201 dogs are bully breeds (28.1%)